### ISSUE TITLE
Weird issue with Sphinx `make docs`

### ISSUE THREAD

**Issue by pydanny** [twoscoops/Creating-and-Distributing-Python-Packages#3]
## Location within the Course

* Chapter: 3
* Lesson: 5
* Language: English

## Description 

```
rm -f docs/femputadora.rst
rm -f docs/modules.rst
sphinx-apidoc -o docs/ femputadora
Creating file docs/femputadora.rst.
Creating file docs/modules.rst.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C docs clean
Removing everything under '_build'...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C docs html
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 9 source files that are out of date
updating environment: 9 added, 0 changed, 0 removed
WARNING: No match found for input: load aiml b
Su mensaje >> hola
WARNING: No match found for input: hola

Su mensaje >> ^Creading sources... [ 44%] historyreading sources... [100%] usage
WARNING: autodoc: failed to import module u'femputadora.femputadora'; the following exception was raised:
Traceback (most recent call last):
File "/Users/sistemas/proyectos/packaging/packaging-env/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
import(modname)
File "/Users/sistemas/proyectos/packaging/femputadora/femputadora/femputadora.py", line 14, in <module>
print kernel.respond(raw_input("Su mensaje >> "))
KeyboardInterrupt

/Users/sistemas/proyectos/packaging/femputadora/docs/index.rst:2: WARNING: Title underline too short.

Welcome to femputadora's documentation!
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/Users/sistemas/proyectos/packaging/femputadora/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in _build/html.
make: * [docs] Interrupt: 2
```

**Comment by pydanny** [comment]
Resolved by fixing cookiecutter-pypackage
